#!/usr/bin/env bash
# generate_readme.sh

BASE_SRC="src/main/java/com/vbforge"

# ── Resolve metadata for a package ───────────────────────────────────────────
# Priority 1: meta.txt in the package  → format: "Easy|Arrays & Hashing Basics"
# Priority 2: auto-derive slug from folder name, default diff+tag
get_meta() {
  local pkg="$1"   # e.g. p_9_Palindrome_Number
  local num="$2"   # e.g. 9
  local title="$3" # e.g. Palindrome Number

  local meta_file="$BASE_SRC/$pkg/meta.txt"
  local slug diff tag

  # Build slug from title (always derived from folder name — always correct)
  slug=$(echo "$title" | tr '[:upper:]' '[:lower:]' | tr ' ' '-')

  if [ -f "$meta_file" ]; then
    # Read difficulty and tag from meta.txt  (format: "Easy|Math, Bits & Misc")
    diff=$(cut -d'|' -f1 < "$meta_file" | tr -d '[:space:]')
    tag=$(cut -d'|' -f2- < "$meta_file" | sed 's/^[[:space:]]*//')
  else
    diff="Easy"
    tag="Uncategorized"
  fi

  echo "${slug}|${diff}|${tag}"
}

# ── Collect and sort packages ─────────────────────────────────────────────────
PACKAGES=$(find "$BASE_SRC" -maxdepth 1 -type d -name 'p_*' \
  | sed 's|.*/||' \
  | sort -t_ -k2 -n)

total=0; solved=0; easy=0; medium=0; hard=0

while IFS= read -r pkg; do
  [ -z "$pkg" ] && continue
  total=$((total + 1))
  num=$(echo "$pkg" | cut -d_ -f2)
  raw=$(echo "$pkg" | cut -d_ -f3-)
  title="${raw//_/ }"
  meta=$(get_meta "$pkg" "$num" "$title")
  diff=$(echo "$meta" | cut -d'|' -f2)
  [ -f "$BASE_SRC/$pkg/Solution.java" ] && solved=$((solved + 1))
  case "$diff" in
    Easy)   easy=$((easy + 1)) ;;
    Medium) medium=$((medium + 1)) ;;
    Hard)   hard=$((hard + 1)) ;;
  esac
done <<< "$PACKAGES"

# ── Write README.md ───────────────────────────────────────────────────────────
{
echo "# LeetCode Solutions — vbforge"
echo ""
echo "> 🤖 *This file is auto-generated by GitHub Actions. Do not edit manually.*"
echo ""
echo "## 📊 Progress"
echo ""
echo "![Solved](https://img.shields.io/badge/Solved-${solved}-brightgreen) ![Total](https://img.shields.io/badge/Total-${total}-blue) ![Easy](https://img.shields.io/badge/Easy-${easy}-green) ![Medium](https://img.shields.io/badge/Medium-${medium}-yellow) ![Hard](https://img.shields.io/badge/Hard-${hard}-red)"
echo ""
echo "## 📋 Problem List"
echo ""
echo "#### Legend: ✅ solved · ⏳ in-progress"
echo ""
echo "| # | Problem | Difficulty | Status | Tag | Solution |"
echo "|---|---------|------------|--------|-----|----------|"

row=1
while IFS= read -r pkg; do
  [ -z "$pkg" ] && continue
  num=$(echo "$pkg" | cut -d_ -f2)
  raw=$(echo "$pkg" | cut -d_ -f3-)
  title="${raw//_/ }"
  meta=$(get_meta "$pkg" "$num" "$title")
  slug=$(echo "$meta" | cut -d'|' -f1)
  diff=$(echo "$meta" | cut -d'|' -f2)
  tag=$(echo "$meta" | cut -d'|' -f3)

  url="https://leetcode.com/problems/${slug}/"
  sol_path="src/main/java/com/vbforge/${pkg}/Solution.java"

  if [ -f "$BASE_SRC/$pkg/Solution.java" ]; then
    status="✅"; sol_link="[Solution.java](${sol_path})"
  else
    status="⏳"; sol_link="—"
  fi

  case "$diff" in
    Easy)   diff_icon="🟢" ;;
    Medium) diff_icon="🟡" ;;
    Hard)   diff_icon="🔴" ;;
    *)      diff_icon=""   ;;
  esac

  echo "| ${row} | [${num}. ${title}](${url}) | ${diff_icon} ${diff} | ${status} | ${tag} | ${sol_link} |"
  row=$((row + 1))
done <<< "$PACKAGES"

echo ""
echo "---"
echo "*Auto-generated. ${solved}/${total} problems solved.*"
} > README.md

echo "[OK] README.md generated — ${total} problems, ${solved} solved."
